name: imtihon4
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  location: ^7.0.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  google_maps_flutter: ^2.7.0
  carousel_slider: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/

